"""
Database package for SupportFlow AI.
"""
from .database import (
    init_db,
    get_connection,
    create_ticket,
    get_all_tickets,
    get_ticket_by_id,
    update_ticket_status,
    save_ticket_analysis,
    get_ticket_analysis,
    save_suggested_response,
    get_suggested_response,
    get_ticket_metrics,
    get_analytics_kpis,
    get_category_distribution,
    get_department_distribution,
    get_priority_distribution,
    get_sentiment_distribution,
    get_daily_ticket_volume,
    get_urgent_tickets,
    get_recent_activity,
)

__all__ = [
    "init_db",
    "get_connection",
    "create_ticket",
    "get_all_tickets",
    "get_ticket_by_id",
    "update_ticket_status",
    "save_ticket_analysis",
    "get_ticket_analysis",
    "save_suggested_response",
    "get_suggested_response",
    "get_ticket_metrics",
    "get_analytics_kpis",
    "get_category_distribution",
    "get_department_distribution",
    "get_priority_distribution",
    "get_sentiment_distribution",
    "get_daily_ticket_volume",
    "get_urgent_tickets",
    "get_recent_activity",
]
